/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const FastingSchedule = IDL.Record({
  'endHour' : IDL.Nat8,
  'startHour' : IDL.Nat8,
});
export const Gender = IDL.Variant({
  'female' : IDL.Null,
  'male' : IDL.Null,
  'diverse' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'heightCm' : IDL.Nat,
  'birthYear' : IDL.Nat,
  'name' : IDL.Text,
  'gender' : Gender,
});
export const DiaryEntry = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'timestamp' : Time,
});
export const MovementDay = IDL.Record({
  'activeMinutes' : IDL.Nat,
  'activityType' : IDL.Variant({
    'gym' : IDL.Null,
    'run' : IDL.Null,
    'bike' : IDL.Null,
    'walk' : IDL.Null,
  }),
  'date' : IDL.Text,
  'intensity' : IDL.Variant({
    'intense' : IDL.Null,
    'light' : IDL.Null,
    'medium' : IDL.Null,
  }),
});
export const NutritionDay = IDL.Record({
  'fat' : IDL.Float64,
  'caloriesConsumed' : IDL.Nat,
  'waterMl' : IDL.Nat,
  'carbs' : IDL.Float64,
  'bodyWeightKg' : IDL.Opt(IDL.Float64),
  'waterLiters' : IDL.Float64,
  'vegetableGrams' : IDL.Opt(IDL.Nat),
  'caloriesBurned' : IDL.Nat,
  'proteinGrams' : IDL.Opt(IDL.Nat),
  'protein' : IDL.Float64,
});
export const SleepDay = IDL.Record({
  'durationHours' : IDL.Float64,
  'qualityScore' : IDL.Int,
});
export const StressDay = IDL.Record({
  'date' : IDL.Text,
  'systolic' : IDL.Nat,
  'diastolic' : IDL.Nat,
  'pulse' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDiaryEntry' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearNutritionDay' : IDL.Func([Time], [], []),
  'clearSleepDay' : IDL.Func([Time], [], []),
  'confirmActivation' : IDL.Func([IDL.Principal], [], []),
  'deleteDiaryEntry' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getCallerFastingSchedule' : IDL.Func(
      [],
      [IDL.Opt(FastingSchedule)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDiaryEntries' : IDL.Func([], [IDL.Vec(DiaryEntry)], ['query']),
  'getIcpAddress' : IDL.Func([], [IDL.Text], ['query']),
  'getMovementDay' : IDL.Func([IDL.Text], [IDL.Opt(MovementDay)], ['query']),
  'getNutritionEntry' : IDL.Func(
      [IDL.Principal, Time],
      [IDL.Opt(NutritionDay)],
      ['query'],
    ),
  'getSleepEntry' : IDL.Func(
      [IDL.Principal, Time],
      [IDL.Opt(SleepDay)],
      ['query'],
    ),
  'getStressDay' : IDL.Func([IDL.Text], [IDL.Opt(StressDay)], ['query']),
  'getTodayNutritionEntry' : IDL.Func([], [IDL.Opt(NutritionDay)], ['query']),
  'getTodaySleepEntry' : IDL.Func([], [IDL.Opt(SleepDay)], ['query']),
  'getUserPaymentAddress' : IDL.Func([], [IDL.Principal], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isUserActivated' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'saveCallerFastingSchedule' : IDL.Func([FastingSchedule], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveMovementDay' : IDL.Func([MovementDay], [], []),
  'saveNutritionDayEntry' : IDL.Func([Time, NutritionDay], [], []),
  'saveSleepDayEntry' : IDL.Func([Time, SleepDay], [], []),
  'saveStressDay' : IDL.Func([StressDay], [], []),
  'setIcpAddress' : IDL.Func([IDL.Text], [], []),
  'updateDiaryEntry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'verifyAndActivate' : IDL.Func([], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const FastingSchedule = IDL.Record({
    'endHour' : IDL.Nat8,
    'startHour' : IDL.Nat8,
  });
  const Gender = IDL.Variant({
    'female' : IDL.Null,
    'male' : IDL.Null,
    'diverse' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'heightCm' : IDL.Nat,
    'birthYear' : IDL.Nat,
    'name' : IDL.Text,
    'gender' : Gender,
  });
  const DiaryEntry = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'timestamp' : Time,
  });
  const MovementDay = IDL.Record({
    'activeMinutes' : IDL.Nat,
    'activityType' : IDL.Variant({
      'gym' : IDL.Null,
      'run' : IDL.Null,
      'bike' : IDL.Null,
      'walk' : IDL.Null,
    }),
    'date' : IDL.Text,
    'intensity' : IDL.Variant({
      'intense' : IDL.Null,
      'light' : IDL.Null,
      'medium' : IDL.Null,
    }),
  });
  const NutritionDay = IDL.Record({
    'fat' : IDL.Float64,
    'caloriesConsumed' : IDL.Nat,
    'waterMl' : IDL.Nat,
    'carbs' : IDL.Float64,
    'bodyWeightKg' : IDL.Opt(IDL.Float64),
    'waterLiters' : IDL.Float64,
    'vegetableGrams' : IDL.Opt(IDL.Nat),
    'caloriesBurned' : IDL.Nat,
    'proteinGrams' : IDL.Opt(IDL.Nat),
    'protein' : IDL.Float64,
  });
  const SleepDay = IDL.Record({
    'durationHours' : IDL.Float64,
    'qualityScore' : IDL.Int,
  });
  const StressDay = IDL.Record({
    'date' : IDL.Text,
    'systolic' : IDL.Nat,
    'diastolic' : IDL.Nat,
    'pulse' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDiaryEntry' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearNutritionDay' : IDL.Func([Time], [], []),
    'clearSleepDay' : IDL.Func([Time], [], []),
    'confirmActivation' : IDL.Func([IDL.Principal], [], []),
    'deleteDiaryEntry' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getCallerFastingSchedule' : IDL.Func(
        [],
        [IDL.Opt(FastingSchedule)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDiaryEntries' : IDL.Func([], [IDL.Vec(DiaryEntry)], ['query']),
    'getIcpAddress' : IDL.Func([], [IDL.Text], ['query']),
    'getMovementDay' : IDL.Func([IDL.Text], [IDL.Opt(MovementDay)], ['query']),
    'getNutritionEntry' : IDL.Func(
        [IDL.Principal, Time],
        [IDL.Opt(NutritionDay)],
        ['query'],
      ),
    'getSleepEntry' : IDL.Func(
        [IDL.Principal, Time],
        [IDL.Opt(SleepDay)],
        ['query'],
      ),
    'getStressDay' : IDL.Func([IDL.Text], [IDL.Opt(StressDay)], ['query']),
    'getTodayNutritionEntry' : IDL.Func([], [IDL.Opt(NutritionDay)], ['query']),
    'getTodaySleepEntry' : IDL.Func([], [IDL.Opt(SleepDay)], ['query']),
    'getUserPaymentAddress' : IDL.Func([], [IDL.Principal], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isUserActivated' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'saveCallerFastingSchedule' : IDL.Func([FastingSchedule], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveMovementDay' : IDL.Func([MovementDay], [], []),
    'saveNutritionDayEntry' : IDL.Func([Time, NutritionDay], [], []),
    'saveSleepDayEntry' : IDL.Func([Time, SleepDay], [], []),
    'saveStressDay' : IDL.Func([StressDay], [], []),
    'setIcpAddress' : IDL.Func([IDL.Text], [], []),
    'updateDiaryEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'verifyAndActivate' : IDL.Func([], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };