/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface NutritionDay {
    fat: number;
    caloriesConsumed: bigint;
    waterMl: bigint;
    carbs: number;
    bodyWeightKg?: number;
    waterLiters: number;
    vegetableGrams?: bigint;
    caloriesBurned: bigint;
    proteinGrams?: bigint;
    protein: number;
}
export interface SleepDay {
    durationHours: number;
    qualityScore: bigint;
}
export type Time = bigint;
export interface StressDay {
    date: string;
    systolic: bigint;
    diastolic: bigint;
    pulse: bigint;
}
export interface MovementDay {
    activeMinutes: bigint;
    activityType: Variant_gym_run_bike_walk;
    date: string;
    intensity: Variant_intense_light_medium;
}
export interface FastingSchedule {
    endHour: number;
    startHour: number;
}
export interface UserProfile {
    heightCm: bigint;
    birthYear: bigint;
    name: string;
    gender: Gender;
}
export enum Gender {
    female = "female",
    male = "male",
    diverse = "diverse"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_gym_run_bike_walk {
    gym = "gym",
    run = "run",
    bike = "bike",
    walk = "walk"
}
export enum Variant_intense_light_medium {
    intense = "intense",
    light = "light",
    medium = "medium"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearNutritionDay(dayTimestamp: Time): Promise<void>;
    clearSleepDay(dayTimestamp: Time): Promise<void>;
    /**
     * / Admin-only: confirms a user's activation status after verifying their 1 ICP payment.
     */
    confirmActivation(user: Principal): Promise<void>;
    getCallerFastingSchedule(): Promise<FastingSchedule | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Returns the owner ICP address. Public — no auth needed so users can see where to send payment.
     */
    getIcpAddress(): Promise<string>;
    getMovementDay(date: string): Promise<MovementDay | null>;
    getNutritionEntry(user: Principal, dayTimestamp: Time): Promise<NutritionDay | null>;
    getSleepEntry(user: Principal, dayTimestamp: Time): Promise<SleepDay | null>;
    getStressDay(date: string): Promise<StressDay | null>;
    getTodayNutritionEntry(): Promise<NutritionDay | null>;
    getTodaySleepEntry(): Promise<SleepDay | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / Checks if a given user is activated.
     * / Admins can check any user; a user can check their own status; guests/others are denied.
     */
    isUserActivated(user: Principal): Promise<boolean>;
    saveCallerFastingSchedule(fastingSchedule: FastingSchedule): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveMovementDay(movementDay: MovementDay): Promise<void>;
    saveNutritionDayEntry(dayTimestamp: Time, entry: NutritionDay): Promise<void>;
    saveSleepDayEntry(dayTimestamp: Time, entry: SleepDay): Promise<void>;
    saveStressDay(stressDay: StressDay): Promise<void>;
    /**
     * / Admin-only: set the owner's ICP payment address.
     */
    setIcpAddress(address: string): Promise<void>;
}
import type { FastingSchedule as _FastingSchedule, Gender as _Gender, MovementDay as _MovementDay, NutritionDay as _NutritionDay, SleepDay as _SleepDay, StressDay as _StressDay, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearNutritionDay(arg0: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearNutritionDay(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearNutritionDay(arg0);
            return result;
        }
    }
    async clearSleepDay(arg0: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearSleepDay(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearSleepDay(arg0);
            return result;
        }
    }
    async confirmActivation(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmActivation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmActivation(arg0);
            return result;
        }
    }
    async getCallerFastingSchedule(): Promise<FastingSchedule | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerFastingSchedule();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerFastingSchedule();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIcpAddress(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getIcpAddress();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIcpAddress();
            return result;
        }
    }
    async getMovementDay(arg0: string): Promise<MovementDay | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMovementDay(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMovementDay(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNutritionEntry(arg0: Principal, arg1: Time): Promise<NutritionDay | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNutritionEntry(arg0, arg1);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNutritionEntry(arg0, arg1);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSleepEntry(arg0: Principal, arg1: Time): Promise<SleepDay | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSleepEntry(arg0, arg1);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSleepEntry(arg0, arg1);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStressDay(arg0: string): Promise<StressDay | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStressDay(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStressDay(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTodayNutritionEntry(): Promise<NutritionDay | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodayNutritionEntry();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodayNutritionEntry();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTodaySleepEntry(): Promise<SleepDay | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodaySleepEntry();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodaySleepEntry();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isUserActivated(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUserActivated(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUserActivated(arg0);
            return result;
        }
    }
    async saveCallerFastingSchedule(arg0: FastingSchedule): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerFastingSchedule(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerFastingSchedule(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n23(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n23(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveMovementDay(arg0: MovementDay): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMovementDay(to_candid_MovementDay_n27(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMovementDay(to_candid_MovementDay_n27(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveNutritionDayEntry(arg0: Time, arg1: NutritionDay): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveNutritionDayEntry(arg0, to_candid_NutritionDay_n31(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveNutritionDayEntry(arg0, to_candid_NutritionDay_n31(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async saveSleepDayEntry(arg0: Time, arg1: SleepDay): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSleepDayEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSleepDayEntry(arg0, arg1);
            return result;
        }
    }
    async saveStressDay(arg0: StressDay): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveStressDay(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveStressDay(arg0);
            return result;
        }
    }
    async setIcpAddress(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setIcpAddress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setIcpAddress(arg0);
            return result;
        }
    }
}
function from_candid_Gender_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_MovementDay_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MovementDay): MovementDay {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_NutritionDay_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NutritionDay): NutritionDay {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MovementDay]): MovementDay | null {
    return value.length === 0 ? null : from_candid_MovementDay_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NutritionDay]): NutritionDay | null {
    return value.length === 0 ? null : from_candid_NutritionDay_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SleepDay]): SleepDay | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StressDay]): StressDay | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FastingSchedule]): FastingSchedule | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    activeMinutes: bigint;
    activityType: {
        gym: null;
    } | {
        run: null;
    } | {
        bike: null;
    } | {
        walk: null;
    };
    date: string;
    intensity: {
        intense: null;
    } | {
        light: null;
    } | {
        medium: null;
    };
}): {
    activeMinutes: bigint;
    activityType: Variant_gym_run_bike_walk;
    date: string;
    intensity: Variant_intense_light_medium;
} {
    return {
        activeMinutes: value.activeMinutes,
        activityType: from_candid_variant_n14(_uploadFile, _downloadFile, value.activityType),
        date: value.date,
        intensity: from_candid_variant_n15(_uploadFile, _downloadFile, value.intensity)
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fat: number;
    caloriesConsumed: bigint;
    waterMl: bigint;
    carbs: number;
    bodyWeightKg: [] | [number];
    waterLiters: number;
    vegetableGrams: [] | [bigint];
    caloriesBurned: bigint;
    proteinGrams: [] | [bigint];
    protein: number;
}): {
    fat: number;
    caloriesConsumed: bigint;
    waterMl: bigint;
    carbs: number;
    bodyWeightKg?: number;
    waterLiters: number;
    vegetableGrams?: bigint;
    caloriesBurned: bigint;
    proteinGrams?: bigint;
    protein: number;
} {
    return {
        fat: value.fat,
        caloriesConsumed: value.caloriesConsumed,
        waterMl: value.waterMl,
        carbs: value.carbs,
        bodyWeightKg: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.bodyWeightKg)),
        waterLiters: value.waterLiters,
        vegetableGrams: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.vegetableGrams)),
        caloriesBurned: value.caloriesBurned,
        proteinGrams: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.proteinGrams)),
        protein: value.protein
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    heightCm: bigint;
    birthYear: bigint;
    name: string;
    gender: _Gender;
}): {
    heightCm: bigint;
    birthYear: bigint;
    name: string;
    gender: Gender;
} {
    return {
        heightCm: value.heightCm,
        birthYear: value.birthYear,
        name: value.name,
        gender: from_candid_Gender_n7(_uploadFile, _downloadFile, value.gender)
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gym: null;
} | {
    run: null;
} | {
    bike: null;
} | {
    walk: null;
}): Variant_gym_run_bike_walk {
    return "gym" in value ? Variant_gym_run_bike_walk.gym : "run" in value ? Variant_gym_run_bike_walk.run : "bike" in value ? Variant_gym_run_bike_walk.bike : "walk" in value ? Variant_gym_run_bike_walk.walk : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    intense: null;
} | {
    light: null;
} | {
    medium: null;
}): Variant_intense_light_medium {
    return "intense" in value ? Variant_intense_light_medium.intense : "light" in value ? Variant_intense_light_medium.light : "medium" in value ? Variant_intense_light_medium.medium : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    female: null;
} | {
    male: null;
} | {
    diverse: null;
}): Gender {
    return "female" in value ? Gender.female : "male" in value ? Gender.male : "diverse" in value ? Gender.diverse : value;
}
function to_candid_Gender_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_MovementDay_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MovementDay): _MovementDay {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_NutritionDay_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NutritionDay): _NutritionDay {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    heightCm: bigint;
    birthYear: bigint;
    name: string;
    gender: Gender;
}): {
    heightCm: bigint;
    birthYear: bigint;
    name: string;
    gender: _Gender;
} {
    return {
        heightCm: value.heightCm,
        birthYear: value.birthYear,
        name: value.name,
        gender: to_candid_Gender_n25(_uploadFile, _downloadFile, value.gender)
    };
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    activeMinutes: bigint;
    activityType: Variant_gym_run_bike_walk;
    date: string;
    intensity: Variant_intense_light_medium;
}): {
    activeMinutes: bigint;
    activityType: {
        gym: null;
    } | {
        run: null;
    } | {
        bike: null;
    } | {
        walk: null;
    };
    date: string;
    intensity: {
        intense: null;
    } | {
        light: null;
    } | {
        medium: null;
    };
} {
    return {
        activeMinutes: value.activeMinutes,
        activityType: to_candid_variant_n29(_uploadFile, _downloadFile, value.activityType),
        date: value.date,
        intensity: to_candid_variant_n30(_uploadFile, _downloadFile, value.intensity)
    };
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fat: number;
    caloriesConsumed: bigint;
    waterMl: bigint;
    carbs: number;
    bodyWeightKg?: number;
    waterLiters: number;
    vegetableGrams?: bigint;
    caloriesBurned: bigint;
    proteinGrams?: bigint;
    protein: number;
}): {
    fat: number;
    caloriesConsumed: bigint;
    waterMl: bigint;
    carbs: number;
    bodyWeightKg: [] | [number];
    waterLiters: number;
    vegetableGrams: [] | [bigint];
    caloriesBurned: bigint;
    proteinGrams: [] | [bigint];
    protein: number;
} {
    return {
        fat: value.fat,
        caloriesConsumed: value.caloriesConsumed,
        waterMl: value.waterMl,
        carbs: value.carbs,
        bodyWeightKg: value.bodyWeightKg ? candid_some(value.bodyWeightKg) : candid_none(),
        waterLiters: value.waterLiters,
        vegetableGrams: value.vegetableGrams ? candid_some(value.vegetableGrams) : candid_none(),
        caloriesBurned: value.caloriesBurned,
        proteinGrams: value.proteinGrams ? candid_some(value.proteinGrams) : candid_none(),
        protein: value.protein
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    female: null;
} | {
    male: null;
} | {
    diverse: null;
} {
    return value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value == Gender.diverse ? {
        diverse: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_gym_run_bike_walk): {
    gym: null;
} | {
    run: null;
} | {
    bike: null;
} | {
    walk: null;
} {
    return value == Variant_gym_run_bike_walk.gym ? {
        gym: null
    } : value == Variant_gym_run_bike_walk.run ? {
        run: null
    } : value == Variant_gym_run_bike_walk.bike ? {
        bike: null
    } : value == Variant_gym_run_bike_walk.walk ? {
        walk: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_intense_light_medium): {
    intense: null;
} | {
    light: null;
} | {
    medium: null;
} {
    return value == Variant_intense_light_medium.intense ? {
        intense: null
    } : value == Variant_intense_light_medium.light ? {
        light: null
    } : value == Variant_intense_light_medium.medium ? {
        medium: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
