/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FastingSchedule { 'endHour' : number, 'startHour' : number }
export type Gender = { 'female' : null } |
  { 'male' : null } |
  { 'diverse' : null };
export interface MovementDay {
  'activeMinutes' : bigint,
  'activityType' : { 'gym' : null } |
    { 'run' : null } |
    { 'bike' : null } |
    { 'walk' : null },
  'date' : string,
  'intensity' : { 'intense' : null } |
    { 'light' : null } |
    { 'medium' : null },
}
export interface NutritionDay {
  'fat' : number,
  'caloriesConsumed' : bigint,
  'waterMl' : bigint,
  'carbs' : number,
  'bodyWeightKg' : [] | [number],
  'waterLiters' : number,
  'vegetableGrams' : [] | [bigint],
  'caloriesBurned' : bigint,
  'proteinGrams' : [] | [bigint],
  'protein' : number,
}
export interface SleepDay { 'durationHours' : number, 'qualityScore' : bigint }
export interface StressDay {
  'date' : string,
  'systolic' : bigint,
  'diastolic' : bigint,
  'pulse' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'heightCm' : bigint,
  'birthYear' : bigint,
  'name' : string,
  'gender' : Gender,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearNutritionDay' : ActorMethod<[Time], undefined>,
  'clearSleepDay' : ActorMethod<[Time], undefined>,
  /**
   * / Admin-only: confirms a user's activation status after verifying their 1 ICP payment.
   */
  'confirmActivation' : ActorMethod<[Principal], undefined>,
  'getCallerFastingSchedule' : ActorMethod<[], [] | [FastingSchedule]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Returns the owner ICP address. Public — no auth needed so users can see where to send payment.
   */
  'getIcpAddress' : ActorMethod<[], string>,
  'getMovementDay' : ActorMethod<[string], [] | [MovementDay]>,
  'getNutritionEntry' : ActorMethod<[Principal, Time], [] | [NutritionDay]>,
  'getSleepEntry' : ActorMethod<[Principal, Time], [] | [SleepDay]>,
  'getStressDay' : ActorMethod<[string], [] | [StressDay]>,
  'getTodayNutritionEntry' : ActorMethod<[], [] | [NutritionDay]>,
  'getTodaySleepEntry' : ActorMethod<[], [] | [SleepDay]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Checks if a given user is activated.
   * / Admins can check any user; a user can check their own status; guests/others are denied.
   */
  'isUserActivated' : ActorMethod<[Principal], boolean>,
  'saveCallerFastingSchedule' : ActorMethod<[FastingSchedule], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveMovementDay' : ActorMethod<[MovementDay], undefined>,
  'saveNutritionDayEntry' : ActorMethod<[Time, NutritionDay], undefined>,
  'saveSleepDayEntry' : ActorMethod<[Time, SleepDay], undefined>,
  'saveStressDay' : ActorMethod<[StressDay], undefined>,
  /**
   * / Admin-only: set the owner's ICP payment address.
   */
  'setIcpAddress' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];